# Generated by Django 3.2.6 on 2022-12-01 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserVoices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('enroll_voice', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'user_voices',
                'unique_together': {('username', 'enroll_voice')},
            },
        ),
    ]
