# Generated by Django 3.2.6 on 2022-12-01 21:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserVoices',
            new_name='UserVoice',
        ),
        migrations.AlterModelTable(
            name='uservoice',
            table='user_voice',
        ),
    ]
