# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: speaker_verification.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1aspeaker_verification.proto\x12\x07\x62ksv.v1\"J\n\x1aSpeakerVerificationRequest\x12\x19\n\x11\x65nroll_utterances\x18\x01 \x03(\x0c\x12\x11\n\tutterance\x18\x02 \x01(\x0c\"A\n\x1bSpeakerVerificationResponse\x12\x12\n\nsimilarity\x18\x01 \x01(\x02\x12\x0e\n\x06\x61\x63\x63\x65pt\x18\x02 \x01(\x08\x32z\n\x1aSpeakerVerificationService\x12\\\n\rSpeakerVerify\x12#.bksv.v1.SpeakerVerificationRequest\x1a$.bksv.v1.SpeakerVerificationResponse\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'speaker_verification_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _SPEAKERVERIFICATIONREQUEST._serialized_start=39
  _SPEAKERVERIFICATIONREQUEST._serialized_end=113
  _SPEAKERVERIFICATIONRESPONSE._serialized_start=115
  _SPEAKERVERIFICATIONRESPONSE._serialized_end=180
  _SPEAKERVERIFICATIONSERVICE._serialized_start=182
  _SPEAKERVERIFICATIONSERVICE._serialized_end=304
# @@protoc_insertion_point(module_scope)
