# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import apps.speaker_verification.speaker_verification_pb2 as speaker__verification__pb2


class SpeakerVerificationServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SpeakerVerify = channel.unary_unary(
                '/bksv.v1.SpeakerVerificationService/SpeakerVerify',
                request_serializer=speaker__verification__pb2.SpeakerVerificationRequest.SerializeToString,
                response_deserializer=speaker__verification__pb2.SpeakerVerificationResponse.FromString,
                )


class SpeakerVerificationServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def SpeakerVerify(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SpeakerVerificationServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SpeakerVerify': grpc.unary_unary_rpc_method_handler(
                    servicer.SpeakerVerify,
                    request_deserializer=speaker__verification__pb2.SpeakerVerificationRequest.FromString,
                    response_serializer=speaker__verification__pb2.SpeakerVerificationResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'bksv.v1.SpeakerVerificationService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class SpeakerVerificationService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def SpeakerVerify(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/bksv.v1.SpeakerVerificationService/SpeakerVerify',
            speaker__verification__pb2.SpeakerVerificationRequest.SerializeToString,
            speaker__verification__pb2.SpeakerVerificationResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
